markdown: redcarpet
paginate: 10
pygments: true
title: A + O
url: http://a-and-o.co

# prose.io configuration
prose:
  media: _media
  metadata:
    _posts:
      - name: title
        field:
          element: text
      - name: author
        field:
          element: select
          label: Author
          options:
            - name: Adam
              value: adam
            - name: Olivia
              value: olivia
      - name: type
        field:
          element: select
          label: Type
          options:
            - name: Post
              value: post
            - name: Photo
              value: photo
            - name: Quote
              value: quote
            - name: Conversation
              value: conversation
      - name: tags
        field:
          alterable: true
          element: multiselect
          label: Tags
      - name: layout
        field:
          element: hidden
          value: post
  rooturl: _posts
  #siteurl: http://a-and-o.co
