markdown: redcarpet
paginate: 5
highlighter: true
title: A + O
baseurl: http://a-and-o.co
exclude: [ 'CNAME', 'Gemfile', 'Gemfile.lock', 'script' ]

# prose.io configuration
prose:
  media: media
  metadata:
    _posts:
      - name: title
        field:
          element: text
      - name: author
        field:
          element: select
          label: Author
          options:
            - name: Olivia
              value: olivia
            - name: Adam
              value: adam
      - name: type
        field:
          element: select
          label: Type
          options:
            - name: Post
              value: post
            - name: Photo
              value: photo
            - name: Quote
              value: quote
            - name: Conversation
              value: conversation
      - name: tags
        field:
          alterable: true
          element: multiselect
          label: Tags
      - name: layout
        field:
          element: hidden
          value: post
  rooturl: _posts
